export const UserRoles = {
   GUEST: 'GUEST',
   PATIENT: 'PATIENT',
   ADMIN: 'ADMIN',
}

export const STORAGE_KEYS = {
   AUTH: 'AUTH',
}
export const item = [
   {
      id: '1',
      name: 'Александра',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '2',
      name: 'Шарапат',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '3',
      name: 'Рустам',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '4',
      name: 'Гулчапчап',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
]

export const appointmentData = [
   {
      id: '2',
      img: 'https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg',
      changeSpecialist: 'Манак Елена',
      serviceSelection: 'Окулист',
      date: '12.01.2023',
      time: '15:00',
      status: 'Cancelled',
   },
   {
      id: '3',
      img: 'https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg',
      changeSpecialist: 'Манак Елена',
      serviceSelection: 'Окулист',
      date: '12.01.2023',
      time: '15:00',
      status: 'Confirmed',
   },
   {
      id: '4',
      img: 'https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg',
      changeSpecialist: 'Манак Елена',
      serviceSelection: 'Окулист',
      date: '12.01.2023',
      time: '15:00',
      status: 'Completed',
   },
]

export const departmentName = [
   'Аллергология',
   'Вакцинация',
   'Гастроэнтерология',
   'Анестезиология',
   'Гинекология',
   'Дерматология',
   'Кардиология',
   'Неврология',
   'Нейрохирургия',
   'Онкология',
   'Ортопедия',
   'Отоларингология',
   'Офтальмология',
   'Проктология',
   'Психотерапия',
   'Пульмонология',
   'Ревматология',
   'Терапия',
   'Урология',
   'Флебология',
   'Флебология',
   'Флебология',
]
