export const item = [
   {
      id: '1',
      name: 'Александра',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '2',
      name: 'Шарапат',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '3',
      name: 'Рустам',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '4',
      name: 'Гулчапчап',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
]
