export const UserRoles = {
   GUEST: 'GUEST',
   USER: 'USER',
   ADMIN: 'ADMIN',
}

export const item = [
   {
      id: '1',
      name: 'Александра',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '2',
      name: 'Шарапат',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '3',
      name: 'Рустам',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
   {
      id: '4',
      name: 'Гулчапчап',
      telNumber: '+996 707 123 456',
      mail: 'saadat@gmail.com',
      serviceSelection: 'Окулист',
      changeSpecialist: 'Манак Елена',
      date: '12.01.2023',
      time: '15:00',
      isChecked: false,
      processedChecked: false,
   },
]

export const appointmentData = [
   {
      id: '2',
      img: 'https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg',
      changeSpecialist: 'Манак Елена',
      serviceSelection: 'Окулист',
      date: '12.01.2023',
      time: '15:00',
      status: 'Cancelled',
   },
   {
      id: '3',
      img: 'https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg',
      changeSpecialist: 'Манак Елена',
      serviceSelection: 'Окулист',
      date: '12.01.2023',
      time: '15:00',
      status: 'Confirmed',
   },
   {
      id: '4',
      img: 'https://expertphotography.b-cdn.net/wp-content/uploads/2020/08/profile-photos-4.jpg',
      changeSpecialist: 'Манак Елена',
      serviceSelection: 'Окулист',
      date: '12.01.2023',
      time: '15:00',
      status: 'Completed',
   },
]

export const patientData = [
   {
      id: '1',
      number: 1,
      name: 'Айназик ',
      sname: ' Адамова',
      telNumber: '+996 707 123 456',
      mail: 'ainazik@gmail.com',
      date: '-',
   },
   {
      id: '2',
      number: 2,
      name: 'Айназик ',
      sname: ' Бакытова',
      telNumber: '+996 707 123 456',
      mail: 'ainazik@gmail.com',
      date: '-',
   },
   {
      id: '3',
      number: 3,
      name: 'Булут ',
      sname: ' Бакыт',
      telNumber: '+996 707 123 456',
      mail: 'ainazik@gmail.com',
      date: '12.01.1985',
   },
   {
      id: '4',
      number: 4,
      name: 'Лейла ',
      sname: ' Асман',
      telNumber: '+996 707 123 456',
      mail: 'ainazik@gmail.com',
      date: '12.12.2012',
   },
]
